name: Alight Organization Build Pipeline

on:
  push:
    branches:
      - main
jobs:
  cicd-pipeline:
    uses: AlightEngineering/ADA-CI-Pipeline/.github/workflows/build-pipeline.yaml@main
    secrets: inherit
