name: Alight Organization CI

on:
  push:
    branches:
      - main
      - develop
jobs:
  cicd-pipeline:
    uses: AlightEngineering/Alight-Digital-Architecture_CI-Pipeline/.github/workflows/cicd.yaml@main
