name: Alight Organization Build Pipeline

on:
  push:
    branches:
      - main
jobs:
  cicd-pipeline:
    uses: AlightEngineering/Alight-Digital-Architecture_CI-Pipeline/.github/workflows/build-pipeline.yaml@main
